name: Periodic Health check

on:
  push:
    branches:
      - dev
  schedule:
    # This will happen every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  Fail:
    runs-on: ubuntu-20.04
    steps:
      - name: Check for not heathy route
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://bold-tree-299.fly.dev/fail
  Success:
    runs-on: ubuntu-20.04
    steps:
      - name: Check for healthy route
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://bold-tree-299.fly.dev/health
