name: Periodic Health check

on:
  # Push if needed for testing the workflow
  # push:
  #   branches:
  #     - dev
  schedule:
    # This will happen every day at 12pm
    - cron: '0 12 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: health check, returns 200
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://bold-tree-299.fly.dev/health
#   Fail:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: health check on /fail, throws an error
#         uses: Jtalk/url-health-check-action@v3.1
#         with:
#           url: https://bold-tree-299.fly.dev/fail
